sylius_grid:
  grids:
    arobases_sylius_rights_management_plugin_role:
      driver:
        name: doctrine/orm
        options:
          class: '%arobases_sylius_rights_management_plugin.model.role.class%'
      sorting:
      fields:
        name:
          type: string
          label: sylius.ui.name
      actions:
        item:
          update:
            type: update
          delete:
            type: delete
        main:
          create:
            type: create